basic functions to enable changing sim params
open-dynamic-robot-initiative/trifinger_simulation pull request #26
Opened 2020-10-10 14:56 UTC by shrutij01

## Description

Added functionality to expose and thereby modify dynamics and visual ppties such as colour/texture of any collision object loaded into the environment, or of any of the links.

## How I Tested

by running all the unit tests

## I fulfilled the following requirements

- [x] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [x] All new functions/classes are documented and existing documentation is updated according to changes.
- [x] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

2020-10-30 14:09 UTC, luator requested changes
Sorry, I completely forgot about this PR :(

2020-10-30 14:09 UTC, luator commented on python/trifinger_simulation/collision_objects.py
> +        then both will get loaded onto the object, and the texture will have
> then both will get loaded onto the object

The current implementation will not set the colour if both are specified. (see also comment on equivalent method in SimFinger).

2020-10-30 14:09 UTC, luator commented on python/trifinger_simulation/collision_objects.py
> +            orientation = [1, 1, 1, 1]
1. I assume this should be `[0, 0, 0, 1]` (= "no rotation").
2. Better directly use this as default above instead of `None`.

2020-10-30 14:09 UTC, luator commented on python/trifinger_simulation/collision_objects.py
> +        **kwargs,
Does this `kwargs` argument has any other purpose apart from passing the the physicsClientId?  If not, I would rather replace it with an explicit argument for that.

2021-06-16 04:56 UTC, shrutij01 commented
Closing this since I think it would be easier to introduce these features on the updated state of the repo than to update these here.

2021-06-16 04:56 UTC, closed without merging