Make compatible with gym 0.23.1
open-dynamic-robot-initiative/trifinger_simulation pull request #81
Opened 2022-05-22 17:04 UTC by nicoguertler

## Description

Adapted to gym version 0.23.1. The following changes were made:

* Adapt setup.py.
* Replace GoalEnv with Env.
* Explicitly set data type of Box spaces to np.float64 (as observations are np.float64 and gym does not ignore this in `contains` anymore).
* Imported gym_wrappers to be able to make reach-v0 environment with gym.make.

## How I Tested

Ran tests with pytest.

2022-05-23 07:06 UTC, luator requested changes
Thanks a lot for fixing this!  The PR needs a bit of cleanup but apart from this it looks good to me.

- There are several `*.swp` files added, which I assume shouldn't be here.  Maybe it would make sense to add it to .gitignore?
- There are some formatting issues (see failing check), please run `black` to fix them.

2022-05-24 10:21 UTC, nicoguertler commented on tests/test_determinism.py
> +import trifinger_simulation.gym_wrapper
You are right, I removed the superfluous import.

2022-05-24 10:22 UTC, nicoguertler commented
Sorry about the swap files. I removed them and added *.swp to .gitignore. I also ran black.

2022-05-24 10:24 UTC, luator commented on .flake8
> +per-file-ignores = tests/test_determinism.py:F401
This is probably not needed anymore?

2022-05-24 11:53 UTC, nicoguertler commented on .flake8
> +per-file-ignores = tests/test_determinism.py:F401
Yes, you are right, sorry.

2022-05-24 12:08 UTC, luator approved these changes

2022-05-24 12:11 UTC, merged

2022-05-24 12:11 UTC, luator commented
Thanks a lot!